import 'package:flutter/material.dart';

enum OccasionCategory {
  all,
  islamic,
  officialHoliday,
  upcoming,
}

class OccasionItem {
  final String id;
  final String title;
  final String subtitle;
  final OccasionCategory category;
  final String hijriDate;
  final String gregorianDate;
  final int estimatedDaysRemaining;
  final bool isOfficialHoliday;
  final String? holidayDuration;
  final String virtues;
  final IconData icon;

  const OccasionItem({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.category,
    required this.hijriDate,
    required this.gregorianDate,
    required this.estimatedDaysRemaining,
    required this.isOfficialHoliday,
    this.holidayDuration,
    required this.virtues,
    required this.icon,
  });
}

class OccasionsData {
  static const List<OccasionItem> allOccasions = [
    OccasionItem(
      id: 'ramadan',
      title: 'غرة شهر رمضان المبارك',
      subtitle: 'شهر القرآن والصيام والقيام والعتق من النيران',
      category: OccasionCategory.islamic,
      hijriDate: '1 رمضان 1448 هـ',
      gregorianDate: 'فبراير / مارس 2027 م',
      estimatedDaysRemaining: 142,
      isOfficialHoliday: false,
      virtues: 'تفتح فيه أبواب الجنان، وتغلق أبواب النيران، وصيامه ركن من أركان الإسلام.',
      icon: Icons.nightlight_rounded,
    ),
    OccasionItem(
      id: 'laylat_qadr',
      title: 'ليلة القدر المباركة',
      subtitle: 'العشر الأواخر من شهر رمضان المعظم',
      category: OccasionCategory.islamic,
      hijriDate: '27 رمضان 1448 هـ',
      gregorianDate: 'مارس 2027 م',
      estimatedDaysRemaining: 168,
      isOfficialHoliday: false,
      virtues: 'خيرٌ من ألف شهر، تتنزل فيها الملائكة والروح، ويستحب فيها قيام الليل والدعاء: اللهم إنك عفو تحب العفو فاعف عني.',
      icon: Icons.auto_awesome_rounded,
    ),
    OccasionItem(
      id: 'eid_fitr',
      title: 'عيد الفطر المبارك',
      subtitle: 'فرحة الصائمين بإتمام الصيام وزكاة الفطر',
      category: OccasionCategory.islamic,
      hijriDate: '1 - 3 شوال 1448 هـ',
      gregorianDate: 'مارس 2027 م',
      estimatedDaysRemaining: 172,
      isOfficialHoliday: true,
      holidayDuration: 'إجازة 3 أيام',
      virtues: 'سنن العيد: الاغتسال، ولبس أحسن الثياب، وأكل تمرات وتراً قبل الخروج للصلاة، والتكبير، وصلة الأرحام.',
      icon: Icons.celebration_rounded,
    ),
    OccasionItem(
      id: 'arafah',
      title: 'يوم عرفة المبارك',
      subtitle: 'وقفة الحجاج على صعيد عرفات الطاهر',
      category: OccasionCategory.islamic,
      hijriDate: '9 ذو الحجة 1448 هـ',
      gregorianDate: 'مايو / يونيو 2027 م',
      estimatedDaysRemaining: 239,
      isOfficialHoliday: true,
      holidayDuration: 'إجازة يوم الوقفة',
      virtues: 'صيامه لغير الحاج يكفر السنة الماضية والسنة القابلة، وخير الدعاء دعاء يوم عرفة: لا إله إلا الله وحده لا شريك له.',
      icon: Icons.mosque_rounded,
    ),
    OccasionItem(
      id: 'eid_adha',
      title: 'عيد الأضحى المبارك',
      subtitle: 'يوم النحر وأيام التشريق المباركة',
      category: OccasionCategory.islamic,
      hijriDate: '10 - 13 ذو الحجة 1448 هـ',
      gregorianDate: 'يونيو 2027 م',
      estimatedDaysRemaining: 240,
      isOfficialHoliday: true,
      holidayDuration: 'إجازة 4 أيام',
      virtues: 'أعظم الأيام عند الله يوم النحر، وسننه ذبح الأضحية، والتكبير المقيد والمطلق، وإدخال السرور على الفقراء والمساكين.',
      icon: Icons.favorite_rounded,
    ),
    OccasionItem(
      id: 'hijri_new_year',
      title: 'رأس السنة الهجرية',
      subtitle: 'ذكرى الهجرة النبوية المباركة من مكة إلى المدينة',
      category: OccasionCategory.islamic,
      hijriDate: '1 محرم 1449 هـ',
      gregorianDate: 'يوليو 2027 م',
      estimatedDaysRemaining: 269,
      isOfficialHoliday: true,
      holidayDuration: 'إجازة رسمية',
      virtues: 'استحضار تضحيات النبي ﷺ وصحابته، ومحاسبة النفس على العام المنصرم، واستقبال العام الجديد بالطاعات.',
      icon: Icons.event_available_rounded,
    ),
    OccasionItem(
      id: 'ashura',
      title: 'يوم عاشوراء وتاسوعاء',
      subtitle: 'اليوم الذي نجى الله فيه موسى عليه السلام وقومه',
      category: OccasionCategory.islamic,
      hijriDate: '9 - 10 محرم 1449 هـ',
      gregorianDate: 'يوليو 2027 م',
      estimatedDaysRemaining: 279,
      isOfficialHoliday: false,
      virtues: 'قال النبي ﷺ: صيام يوم عاشوراء أحتسب على الله أن يكفر السنة التي قبله، ويستحب صيام تاسوعاء قبله مخالفةً لأهل الكتاب.',
      icon: Icons.wb_sunny_rounded,
    ),
    OccasionItem(
      id: 'prophet_birthday',
      title: 'المولد النبوي الشريف',
      subtitle: 'ذكرى ميلاد خاتم الأنبياء والمرسلين ﷺ',
      category: OccasionCategory.islamic,
      hijriDate: '12 ربيع الأول 1449 هـ',
      gregorianDate: 'سبتمبر 2027 م',
      estimatedDaysRemaining: 340,
      isOfficialHoliday: true,
      holidayDuration: 'إجازة رسمية',
      virtues: 'الإكثار من الصلاة والسلام على الحبيب المصطفى ﷺ، ومدارسة سيرته العطرة والتخلق بأخلاقه.',
      icon: Icons.stars_rounded,
    ),
    OccasionItem(
      id: 'isra_miraj',
      title: 'ليلة الإسراء والمعراج',
      subtitle: 'معجزة الإسراء بالنبي ﷺ وفرض الصلوات الخمس',
      category: OccasionCategory.islamic,
      hijriDate: '27 رجب 1448 هـ',
      gregorianDate: 'يناير / فبراير 2027 م',
      estimatedDaysRemaining: 110,
      isOfficialHoliday: false,
      virtues: 'تذكر فضل الصلاة التي فُرضت في السماء السابعة، واستشعار مكانة المسجد الحرام والمسجد الأقصى.',
      icon: Icons.flight_takeoff_rounded,
    ),
    OccasionItem(
      id: 'nisf_shaban',
      title: 'ليلة النصف من شعبان',
      subtitle: 'ليلة تحويل القبلة ورفع الأعمال إلى الله',
      category: OccasionCategory.islamic,
      hijriDate: '15 شعبان 1448 هـ',
      gregorianDate: 'فبراير 2027 م',
      estimatedDaysRemaining: 128,
      isOfficialHoliday: false,
      virtues: 'يطلع الله فيها إلى خلقه فيغفر للمؤمنين إلا لمشرك أو مشاحن، ويستحب فيها الاستغفار وسلامة الصدر والصيام.',
      icon: Icons.brightness_medium_rounded,
    ),
    OccasionItem(
      id: 'october_victory',
      title: 'عيد القوات المسلحة (6 أكتوبر)',
      subtitle: 'ذكرى نصر أكتوبر المجيد',
      category: OccasionCategory.officialHoliday,
      hijriDate: 'ربيع الآخر',
      gregorianDate: '6 أكتوبر',
      estimatedDaysRemaining: 5,
      isOfficialHoliday: true,
      holidayDuration: 'إجازة رسمية مدفوعة',
      virtues: 'يوم العزة والكرامة والتضحية والشهداء في سبيل حماية الوطن والأمة.',
      icon: Icons.military_tech_rounded,
    ),
    OccasionItem(
      id: 'labor_day',
      title: 'عيد العمال',
      subtitle: 'تكريم سواعد العمل والإنتاج',
      category: OccasionCategory.officialHoliday,
      hijriDate: 'ذو القعدة',
      gregorianDate: '1 مايو',
      estimatedDaysRemaining: 212,
      isOfficialHoliday: true,
      holidayDuration: 'إجازة رسمية مدفوعة',
      virtues: 'حث الإسلام على العمل وإتقان الصنعة: إن الله يحب إذا عمل أحدكم عملاً أن يتقنه.',
      icon: Icons.handshake_rounded,
    ),
    OccasionItem(
      id: 'revolution_23_july',
      title: 'ثورة 23 يوليو',
      subtitle: 'ذكرى الثورة وبناء الدولة الحديثة',
      category: OccasionCategory.officialHoliday,
      hijriDate: 'محرم',
      gregorianDate: '23 يوليو',
      estimatedDaysRemaining: 295,
      isOfficialHoliday: true,
      holidayDuration: 'إجازة رسمية مدفوعة',
      virtues: 'يوم وطني للاحتفاء بالنهضة والاستقلال والتنمية.',
      icon: Icons.flag_rounded,
    ),
    OccasionItem(
      id: 'coptic_christmas',
      title: 'عيد الميلاد المجيد',
      subtitle: 'عطلة رسمية بمناسبة عيد الميلاد',
      category: OccasionCategory.officialHoliday,
      hijriDate: 'رجب',
      gregorianDate: '7 يناير',
      estimatedDaysRemaining: 98,
      isOfficialHoliday: true,
      holidayDuration: 'إجازة رسمية مدفوعة',
      virtues: 'عطلة رسمية تعزز أواصر الإخاء والتعايش والسلام.',
      icon: Icons.church_rounded,
    ),
    OccasionItem(
      id: 'sinai_liberation',
      title: 'عيد تحرير سيناء',
      subtitle: 'ذكرى استرداد أرض الفيروز كاملة',
      category: OccasionCategory.officialHoliday,
      hijriDate: 'شوال',
      gregorianDate: '25 أبريل',
      estimatedDaysRemaining: 206,
      isOfficialHoliday: true,
      holidayDuration: 'إجازة رسمية مدفوعة',
      virtues: 'يوم تخليد بطولات التحرير واستعادة السيادة والكرامة الوطنية.',
      icon: Icons.terrain_rounded,
    ),
  ];
}
